version: '3.8'

services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "8050:8000" # Menerima lalu lintas dari Nginx VPS di port 8050
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      MYSQL_HOST: host.docker.internal # Sesuaikan jika menggunakan DB native
      MYSQL_PORT: 3306
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: nyawit-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 200M
