"""Add dynamic dashboard fields

Revision ID: 0030ae691918
Revises: cb06d2f936d3
Create Date: 2026-06-07 20:23:36.701364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0030ae691918'
down_revision: Union[str, Sequence[str], None] = 'cb06d2f936d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_logs', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('inference_logs', sa.Column('results_json', sa.JSON(), nullable=True))
    op.add_column('inference_logs', sa.Column('healthy_count', sa.Integer(), nullable=True))
    op.add_column('inference_logs', sa.Column('small_count', sa.Integer(), nullable=True))
    op.add_column('inference_logs', sa.Column('yellow_count', sa.Integer(), nullable=True))
    op.add_column('inference_logs', sa.Column('dead_count', sa.Integer(), nullable=True))
    op.alter_column('inference_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('user_notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('inference_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_column('inference_logs', 'dead_count')
    op.drop_column('inference_logs', 'yellow_count')
    op.drop_column('inference_logs', 'small_count')
    op.drop_column('inference_logs', 'healthy_count')
    op.drop_column('inference_logs', 'results_json')
    op.drop_column('inference_logs', 'image_url')
    # ### end Alembic commands ###
