"""create_vra_recommendations

Revision ID: 93155ea580d2
Revises: cb06d2f936d3
Create Date: 2026-06-09 16:23:34.122917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93155ea580d2'
down_revision: Union[str, Sequence[str], None] = 'cb06d2f936d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vra_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inference_log_id', sa.Integer(), nullable=False),
    sa.Column('healthy_count', sa.Integer(), nullable=True),
    sa.Column('yellowing_count', sa.Integer(), nullable=True),
    sa.Column('small_canopy_count', sa.Integer(), nullable=True),
    sa.Column('dead_count', sa.Integer(), nullable=True),
    sa.Column('overall_priority', sa.String(length=50), nullable=False),
    sa.Column('primary_concern', sa.String(length=255), nullable=True),
    sa.Column('secondary_concern', sa.String(length=255), nullable=True),
    sa.Column('recommended_programs', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inference_log_id'], ['inference_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inference_log_id')
    )
    op.create_index(op.f('ix_vra_recommendations_id'), 'vra_recommendations', ['id'], unique=False)
    op.alter_column('inference_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('user_notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('inference_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_index(op.f('ix_vra_recommendations_id'), table_name='vra_recommendations')
    op.drop_table('vra_recommendations')
    # ### end Alembic commands ###
