"""Add profile and role fields

Revision ID: f423dfec5a89
Revises: ba49bd6e81fe
Create Date: 2026-05-20 11:38:03.503283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f423dfec5a89'
down_revision: Union[str, Sequence[str], None] = 'ba49bd6e81fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
