"""Add user_id multitenancy logic, remove activity_logs

Revision ID: f892c4a76e61
Revises: 03587d8c6dc9
Create Date: 2026-06-14 11:27:30.271745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f892c4a76e61'
down_revision: Union[str, Sequence[str], None] = '03587d8c6dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.add_column('inference_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('inference_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_foreign_key(None, 'inference_logs', 'users', ['user_id'], ['id'])
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('reports', 'company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.alter_column('user_notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('vra_recommendations', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vra_recommendations', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('user_notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('reports', 'company_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('reports', 'user_id')
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_constraint(None, 'inference_logs', type_='foreignkey')
    op.alter_column('inference_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_column('inference_logs', 'user_id')
    op.create_table('activity_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('activity_logs_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('activity_logs_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    # ### end Alembic commands ###
